Version 1.2
JuliGames/JuliGamesCore pull request #11
Opened 2023-01-29 15:04 UTC by TureBentzin

2023-02-02 21:08 UTC, TureBentzin commented
This will be further delayed because of #16 #15 #14

2023-02-06 15:20 UTC, Bommels05 requested changes
With this PR the Core finally really leaves the Beta!

2023-02-06 15:20 UTC, Bommels05 commented on API/src/main/java/net/juligames/core/api/jdbi/DBData.java
> + * with 2.0 - TANDANA
Tandana...Tandana Kerman?

2023-02-06 15:20 UTC, Bommels05 commented on API/src/main/java/net/juligames/core/api/jdbi/DBData.java
> + * @apiNote This is an experimental Idea to allow users of the Core to store data only for meant to be dealt with into
Drunk javadoc?

2023-02-06 15:20 UTC, Bommels05 commented on AdventureCore/src/main/java/net/juligames/core/adventure/JDBITagAdapter.java
> +            case TEXT -> {
Please refrain from using rusty kotlin

2023-02-06 15:20 UTC, Bommels05 commented on Core/src/main/java/net/juligames/core/Core.java
> -        coreLogger.setDebug(true);
A bit late

2023-02-06 15:20 UTC, Bommels05 commented on Core/src/main/java/net/juligames/core/config/CoreConfiguration.java
> +                Core.getInstance().getCoreLogger().debug("OVERRIDE: set " + entry.getKey() + "from " + old + " to " + entry.getValue());
It looks like this is the first release version of the co(ö)re

2023-02-06 15:20 UTC, Bommels05 commented on Master/src/main/java/net/juligames/core/master/CoreMaster.java
> +        API.get().getCommandApi().sendCommand("svconfig", master);
Eco fix?

2023-02-06 15:20 UTC, Bommels05 commented on PaperAPI/src/main/java/net/juligames/core/paper/perms/PermissionCheckReturn.java
> +     * Indicates if the Check was positive or negative. If wasSuccessful returns true, this will always return false
```suggestion
     * Indicates if the Check was positive or negative. If wasSuccessful returns false, this will always return false
```

2023-02-08 07:25 UTC, TureBentzin commented
@Bommels05 all requested changes where committed

2023-02-10 14:05 UTC, Bommels05 approved these changes
Thank you for fixing what I reported!

2023-02-10 14:25 UTC, Bommels05 submitted a review, later dismissed
!

2023-02-10 16:10 UTC, merged