Version 1.3
JuliGames/JuliGamesCore pull request #20
Opened 2023-02-11 16:28 UTC by TureBentzin

This Version delivers a critical fix for 1.2

Changes:
- MiniMessageInjection (fixed)
- New Replacement System and API
- Better JavaDoc
- Small fixes
- Configurations can now be copied

2023-02-11 16:35 UTC, TureBentzin commented on .gitignore
>  config/messageSystem.properties=
this file needs a rework with the next update

2023-02-12 11:03 UTC, Bommels05 requested changes
Good Work! If I ignore the Snapshot errors this PR just brings bug fixes and tiny features!

2023-02-12 11:03 UTC, Bommels05 commented on AdventureAPI/src/main/java/net/juligames/core/adventure/api/AdventureAPI.java
> +    String API_VERSION = "1.3-SNAPSHOT";
```suggestion
    String API_VERSION = "1.3";
```

2023-02-12 11:03 UTC, Bommels05 commented on AdventureCore/src/main/java/net/juligames/core/adventure/AdventureCore.java
> +    final String CORE_VERSION = "1.3-SNAPSHOT";
```suggestion
    final String CORE_VERSION = "1.3";
```

2023-02-12 11:03 UTC, Bommels05 commented on AdventureCore/src/main/java/net/juligames/core/adventure/CoreAdventureTagManager.java
> +
```suggestion
```

2023-02-12 11:03 UTC, Bommels05 commented on Core/src/main/java/net/juligames/core/Core.java
> +    public static final String CORE_VERSION_NUMBER = "1.3-SNAPSHOT";
```suggestion
    public static final String CORE_VERSION_NUMBER = "1.3";
```

2023-02-12 11:03 UTC, Bommels05 commented on Core/src/main/java/net/juligames/core/Core.java
> +    private static final String BUILD_VERSION = "1.3-SNAPSHOT"; //POM VERSION
```suggestion
    private static final String BUILD_VERSION = "1.3"; //POM VERSION
```

2023-02-12 11:06 UTC, Bommels05 approved these changes

2023-02-12 11:06 UTC, merged